name: Feature Branch

on:
  push:
    branches:
      - "main"
jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t migrator .

      - name: Run Docker image
        run: |
          docker run migrator
